### ISSUE TITLE
Face render bug if use Snorkel from ARTIFACTS mod

### ISSUE THREAD

**Issue by joshepDAM1986** [SmartStreamLabs/mysticrift_pharaohs_legacy#1]
When i install this mod my character face turns invisible when use the Snorkel accesory from ARTIFACTS Mod...

**Comment by SmartStreamLabs** [comment]
Hi joshepDAM1986! very sorry that you are experiencing this. can you give us more details of your problem? Unfortunately, we can't do much with this information.

Next:

Photo of the bug (not required)

Mod link (ARTIFACTS Mod)

More details.

We are happy to help you, Smartstreamlabs dev team

**Comment by GuXiaoYu1999** [comment]
Hi, as the main developer of the mod: MysticRift: Pharaohs Legacy I can tell you that this bug has nothing to do with our mod.  ( we tested it with every version with the ( Artifacts mod )

You should report these types of bugs to the makers of: Artifacts https://github.com/ochotonida/artifacts/issues

Sorry for the inconvenience, Mei
